package lr2touch;
import bms.player.beatoraja.*;import bms.player.beatoraja.config.SkinConfiguration;import bms.player.beatoraja.skin.*;import bms.player.beatoraja.select.MusicSelector;
import javax.swing.*;import java.awt.*;import java.lang.reflect.*;import java.nio.file.*;import java.util.*;
/** Metadata-only skin editor; the game's own custom-option setters edit an isolated draft. */
public final class SkinPanel extends JPanel {
 final Touch ui;final JPanel body=Touch.panel(new GridBagLayout());java.util.List<SkinHeader> headers=new ArrayList<>();SkinConfiguration engine;SkinType type=SkinType.PLAY_7KEYS;SkinConfig draft;SkinHeader selected;String owner="";boolean loading;int row;
 SkinPanel(Touch ui){super(new BorderLayout());this.ui=ui;setOpaque(false);add(TouchWidgets.scroll(body));}
 static Object get(Object o,String n)throws Exception{for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{Field f=c.getDeclaredField(n);f.setAccessible(true);return f.get(o);}catch(NoSuchFieldException e){}throw new NoSuchFieldException(n);}
 static void set(Object o,String n,Object value)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);f.set(o,value);}
 static Object invoke(Object o,String n,Class<?>[] types,Object...args)throws Exception{for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{Method m=c.getDeclaredMethod(n,types);m.setAccessible(true);return m.invoke(o,args);}catch(NoSuchMethodException e){}throw new NoSuchMethodException(n);}
 static Object invoke(Object o,String n)throws Exception{return invoke(o,n,new Class<?>[0]);}
 static SkinConfig copy(SkinConfig source)throws Exception{return ProfileRestart.JSON.readValue(ProfileRestart.JSON.writeValueAsBytes(source),SkinConfig.class);}
 void addRow(Component c){GridBagConstraints g=new GridBagConstraints();g.gridx=0;g.gridy=row++;g.weightx=1;g.fill=GridBagConstraints.HORIZONTAL;g.insets=new Insets(0,0,18,0);body.add(c,g);}
 void status(String text){body.removeAll();row=0;addRow(Touch.label(text,26,0));body.revalidate();body.repaint();}
 void open(){if(loading)return;if(Touch.preview||!(ui.attachedMain instanceof MainController)){status("START THE GAME TO EDIT INSTALLED SKINS");return;}MainController main=(MainController)ui.attachedMain;if(!(main.getCurrentState() instanceof MusicSelector)){status("RETURN TO SONG SELECTION TO EDIT SKINS");return;}if(engine!=null&&owner.equals(main.getPlayerConfig().getId())){render();return;}loading=true;status("READING INSTALLED SKIN HEADERS…");new SwingWorker<java.util.List<SkinHeader>,Void>(){protected java.util.List<SkinHeader> doInBackground()throws Exception{engine=new SkinConfiguration(main,main.getPlayerConfig());invoke(engine,"loadAllSkins");return new ArrayList<>((java.util.List<SkinHeader>)SkinPanel.get(engine,"allSkins"));}protected void done(){loading=false;try{headers=get();owner=main.getPlayerConfig().getId();loadType(main);}catch(Exception e){engine=null;status("SKIN HEADERS COULD NOT BE READ: "+e.getClass().getSimpleName());}}}.execute();}
 void loadType(MainController main){try{SkinConfig current=main.getPlayerConfig().getSkin()[type.getId()];selected=null;if(current!=null&&current.getPath()!=null)for(SkinHeader h:headers)if(h.getSkinType()==type&&h.getPath().normalize().equals(Paths.get(current.getPath()).normalize())){selected=h;break;}draft=current==null?new SkinConfig():copy(current);if(selected!=null)bind();render();}catch(Exception e){status("SKIN SETTINGS UNAVAILABLE: "+e.getClass().getSimpleName());}}
 void bind()throws Exception{if(draft.getProperties()==null)draft.setProperties(new SkinConfig.Property());set(engine,"config",draft);set(engine,"selectedSkinHeader",selected);set(engine,"customOptions",new ArrayList<>());invoke(engine,"updateCustomOptions");invoke(engine,"updateCustomFiles");invoke(engine,"updateCustomOffsets");}
 void choose(SkinHeader header){try{selected=header;draft=new SkinConfig(header.getPath().toString());draft.setProperties(new SkinConfig.Property());MainController main=(MainController)ui.attachedMain;for(SkinConfig past:main.getPlayerConfig().getSkinHistory())if(header.getPath().toString().equals(past.getPath())){draft=copy(past);break;}bind();render();}catch(Exception e){status("COULD NOT READ THIS SKIN'S OPTIONS");}}
 void render(){try{body.removeAll();row=0;String[] categories={"GAMEPLAY","MUSIC SELECT","DECIDE","RESULT","COURSE RESULT","KEY CONFIG","SKIN SELECT","THEME"};SkinType[] categoryTypes={SkinType.PLAY_7KEYS,SkinType.MUSIC_SELECT,SkinType.DECIDE,SkinType.RESULT,SkinType.COURSE_RESULT,SkinType.KEY_CONFIG,SkinType.SKIN_SELECT,SkinType.THEME};int cat=0;for(int i=1;i<categoryTypes.length;i++)if(type==categoryTypes[i])cat=i;JPanel top=Touch.panel(new GridLayout(1,2,16,0));top.add(TouchWidgets.option(ui,"Main category",categories,cat,n->{type=categoryTypes[n];loadType((MainController)ui.attachedMain);}));if(type.isPlay()){SkinType[] modes=Arrays.stream(SkinType.values()).filter(SkinType::isPlay).toArray(SkinType[]::new);top.add(TouchWidgets.option(ui,"Subcategory",Arrays.stream(modes).map(SkinType::getName).toArray(String[]::new),Arrays.asList(modes).indexOf(type),n->{type=modes[n];loadType((MainController)ui.attachedMain);}));}addRow(top);
 java.util.List<SkinHeader> available=new ArrayList<>();for(SkinHeader h:headers)if(h.getSkinType()==type)available.add(h);String[] names=new String[available.size()+1];names[0]="SELECT A SKIN";int current=0;for(int i=0;i<available.size();i++){names[i+1]=available.get(i).getName();if(available.get(i)==selected)current=i+1;}addRow(TouchWidgets.option(ui,"Skin",names,current,n->{if(n>0)choose(available.get(n-1));}));
 if(selected!=null){addRow(Touch.label("SKIN-SPECIFIC SETTINGS",26,Font.BOLD));JPanel options=Touch.panel(new GridLayout(0,3,14,18));for(Object item:(java.util.List<?>)get(engine,"customOptions")){String name=(String)invoke(item,"getCategoryName");int value=(Integer)invoke(item,"getvalue");if(item.getClass().getSimpleName().equals("CustomOffsetItem")){options.add(TouchWidgets.number(ui,name,value,(Integer)invoke(item,"getMin"),(Integer)invoke(item,"getMax"),"",v->update(item,v)));}else{String[] labels=item.getClass().getSimpleName().equals("CustomOptionItem")?(String[])get(item,"values"):((java.util.List<String>)get(item,"displayValues")).toArray(new String[0]);options.add(TouchWidgets.option(ui,name,labels,value,v->update(item,v)));}}while(options.getComponentCount()%3!=0)options.add(Touch.panel(new BorderLayout()));addRow(options);addRow(TouchWidgets.half(ui.button("Apply skin settings",this::apply)));}
 addRow(Touch.label("APPLIES WHEN THIS GAME SCREEN NEXT LOADS. SOUND SET IS EXCLUDED.",24,0));GridBagConstraints tail=new GridBagConstraints();tail.gridy=row;tail.weighty=1;body.add(Touch.panel(new BorderLayout()),tail);ui.themeTree(body);body.revalidate();body.repaint();
 }catch(Exception e){status("COULD NOT DISPLAY SKIN SETTINGS: "+e.getClass().getSimpleName());}}
 void update(Object item,int value){try{invoke(item,"setValue",new Class<?>[]{int.class},value);}catch(Exception e){ui.message("SKIN OPTION COULD NOT BE UPDATED");}}
 void apply(){if(selected==null)return;try{SkinConfig saved=copy(draft);SkinType target=type;String profile=owner;ui.command(o->{MainController main=(MainController)o;if(!(main.getCurrentState() instanceof MusicSelector)||!main.getPlayerConfig().getId().equals(profile)){ui.message("RETURN TO THE SAME PROFILE'S SONG SELECTION TO APPLY");return;}PlayerConfig player=main.getPlayerConfig();Path source=Paths.get(main.getConfig().getPlayerpath(),profile,"config_player.json");if(Files.isRegularFile(source)){Path backup=Touch.base.resolve("backups").resolve("skin-"+UUID.randomUUID());Files.createDirectories(backup);Files.copy(source,backup.resolve("config_player.json"));Files.writeString(backup.resolve("RESTORE.txt"),"With the game closed, restore config_player.json to:\n"+source.toAbsolutePath());}SkinConfig previous=player.getSkin()[target.getId()];if(previous!=null&&previous.getPath()!=null){java.util.List<SkinConfig> history=new ArrayList<>(Arrays.asList(player.getSkinHistory()));history.removeIf(c->previous.getPath().equals(c.getPath()));history.add(copy(previous));player.setSkinHistory(history.toArray(new SkinConfig[0]));}player.getSkin()[target.getId()]=saved;main.saveConfig();ui.message("SKIN SETTINGS SAVED. THEY APPLY ON THE NEXT SCREEN LOAD.");});}catch(Exception e){ui.message("COULD NOT PREPARE SKIN SETTINGS");}}
}
